# Generated by Django 2.0.8 on 2020-08-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='experience',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
