# Generated by Django 2.0.8 on 2020-08-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200815_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
