# Generated by Django 2.0.8 on 2018-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id_cnt',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id_cnt',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skills',
            name='id_cnt',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
