# Generated by Django 2.0.8 on 2020-08-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id_cnt', models.AutoField(primary_key=True, serialize=False)),
                ('insti_name', models.CharField(default='', max_length=200)),
                ('s_year', models.IntegerField(default=0)),
                ('e_year', models.IntegerField(default=0)),
                ('degree', models.CharField(default='', max_length=150)),
                ('score', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id_cnt', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=150)),
                ('title', models.CharField(default='', max_length=200)),
                ('s_year', models.IntegerField(default=0)),
                ('e_year', models.IntegerField(default=0)),
                ('work', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id_cnt', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
    ]
