# Generated by Django 2.0.8 on 2020-08-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_education_experience_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
