# Generated by Django 2.0.8 on 2020-08-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200815_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id_cnt', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
    ]
